### ISSUE TITLE
RoadMap to 1.0

### ISSUE THREAD

**Issue by xannor** [xannor/ha_shinobicctv#1]
TODO:

- [ ] push/pull motion events
- [ ] cleanup expected responses
- [ ] ensure entities persist correctly
- [ ] pickup change events from Shinobi
- [ ] figure out steps needed to support 2 factor auth
